---
apiVersion: v2
appVersion: v24.12.1
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
icon: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png
home: https://github.com/djjudas21/charts/tree/master/charts/homer
name: homer
version: 8.2.3
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/bastienwirtz/homer
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
dependencies:
  - name: common
    repository: http://bjw-s.github.io/helm-charts/
    version: 0.2.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to Homer v24.12.1
