apiVersion: v2
type: application
name: jellyfin
description: Your media, your server, your way
version: 3.2.6
appVersion: 10.10.6
kubeVersion: '>=1.20.0-0'
home: https://jellyfin.org/
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg
keywords:
  - jellyfin
  - media-server
  - plex
sources:
  - https://github.com/jellyfin/jellyfin
  - https://github.com/djjudas21/charts/tree/main/charts/jellyfin
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
    url: https://github.com/djjudas21
dependencies: []
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to Jellyfin v10.10.6
