apiVersion: v2
name: graphite-exporter
description: A Prometheus exporter for metrics exported in the Graphite plaintext protocol
type: application
version: 0.1.6
appVersion: "v0.12.3"
home: https://github.com/djjudas21/charts/tree/master/charts/graphite-exporter
icon: https://graphiteapp.org/img/apple-touch-icon-144x144.png
keywords:
  - graphite
  - prometheus
  - monitoring
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
sources:
  - https://github.com/prometheus/graphite_exporter
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Fix chart URL
