---
apiVersion: v2
appVersion: 2.4.13
description: An Application dashboard and launcher
name: heimdall
version: 8.5.1
kubeVersion: ">=1.16.0-0"
keywords:
  - heimdall
home: https://github.com/djjudas21/charts/tree/master/charts/heimdall
icon: https://i.imgur.com/mM4tcO5.png
sources:
  - https://hub.docker.com/r/linuxserver/heimdall/
  - https://github.com/linuxserver/heimdall
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
dependencies:
  - name: common
    repository: http://bjw-s.github.io/helm-charts/
    version: 0.1.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Convert to djjudas21
