{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  ingress:
    - ports:
        - port: 8096
      from:
        - podSelector:
            matchLabels:
              {{- include "common.labels.matchLabels" . | nindent 14 }}
              {{- with .Values.podLabels }}{{ toYaml . | nindent 14 }}{{ end }}
    {{- if .Values.networkPolicy.allowExternal }}
        - podSelector:
            matchLabels:
              network-policies.kubernetes.io/{{ include "common.names.fullname" . }}-access: required
    {{- end }}
    {{- with .Values.networkPolicy.ingress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or (not .Values.networkPolicy.allowAllOutbound) .Values.networkPolicy.egress }}
  egress: {{ if not .Values.networkPolicy.egress }}{}{{ end }}
    {{- with .Values.networkPolicy.egress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}{{ toYaml . | nindent 6 }}{{ end }}
  policyTypes:
    - Ingress
  {{- if or (not .Values.networkPolicy.allowAllOutbound) .Values.networkPolicy.egress }}
    - Egress
  {{- end }}
{{- end }}
