---
apiVersion: v2
name: ecowitt-exporter
description: A Prometheus & InfluxDB exporter for Ecowitt weather stations
type: application
version: 0.5.4
appVersion: "0.5.3"
keywords:
  - ecowitt
  - weather
  - helm
  - prometheus
  - exporter
home: https://github.com/djjudas21/charts/tree/master/charts/ecowitt-exporter
icon: https://user-images.githubusercontent.com/7027842/110340181-44219c80-8029-11eb-9baf-6889de873405.png
sources:
  - https://github.com/djjudas21/ecowitt-exporter
  - https://hub.docker.com/r/djjudas21/ecowitt-exporter
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Fix calculation of UK DAQI
