{{- if $.Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lldap.fullname" . }}-data
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  {{ if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}