---
apiVersion: v2
name: nova-exporter
description: A Prometheus exporter for Fairwinds Nova
type: application
version: 0.1.9
appVersion: "0.0.6"
keywords:
  - nova
  - helm
  - prometheus
  - exporter
home: https://github.com/djjudas21/charts/tree/master/charts/nova-exporter
icon: https://raw.githubusercontent.com/FairwindsOps/nova/master/img/logo.png
sources:
  - https://github.com/djjudas21/nova-exporter
  - https://hub.docker.com/r/djjudas21/nova-exporter
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to nova-exporter 0.0.6
