apiVersion: v2
appVersion: "0.23.1"
description: Keep track of your inventory of 3D-printer filament spools.
name: spoolman
version: 0.1.4
type: application
keywords:
  - database
  - service
  - inventory
  - 3dprinting
  - filament
home: https://github.com/djjudas21/charts/tree/master/charts/spoolman
icon: https://raw.githubusercontent.com/Donkie/Spoolman/refs/heads/master/client/icons/spoolman.svg
sources:
  - https://github.com/Donkie/Spoolman/tree/master
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to Spoolman v0.23.1
