---
apiVersion: v2
name: connectbox-exporter
description: Prometheus exporter for Compal CH7465LG cable modems

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
keywords:
  - connectbox
  - virgin
  - cable
  - modem
  - router
  - prometheus
  - exporter
home: https://github.com/djjudas21/charts/tree/master/charts/connectbox-exporter
icon: https://user-images.githubusercontent.com/7027842/110340181-44219c80-8029-11eb-9baf-6889de873405.png
sources:
  - https://github.com/djjudas21/connectbox-prometheus
  - https://hub.docker.com/r/djjudas21/connectbox-prometheus
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial release
