apiVersion: v2
name: smtp-relay
description: An SMTP smarthost relay for Kubernetes
type: application
version: 0.6.1
appVersion: "0.10.0"
home: https://github.com/djjudas21/charts/tree/main/charts/smtp-relay
keywords:
  - smtp
  - relay
  - smarthost
  - postfix
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
sources:
  - https://github.com/djjudas21/smtp-relay
  - https://hub.docker.com/r/djjudas21/smtp-relay
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Run container on high port
