---
# Source: jellyfin/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-mediavol-movies
  labels:
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
    jellyfin-volume: movies
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Ti
  nfs:
    path: /nas/movies
    server: my-nfs-server.example.com
---
# Source: jellyfin/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-mediavol-musics
  labels:
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
    jellyfin-volume: musics
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Ti
  nfs:
    path: /nas/musics
    server: my-nfs-server.example.com
---
# Source: jellyfin/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-mediavol-movies
  labels:
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
      jellyfin-volume: movies
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 8Ti
---
# Source: jellyfin/templates/storage-media.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-mediavol-musics
  labels:
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
      jellyfin-volume: musics
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 8Ti
