#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/4d09009bf809b2ce3c06225f61cf229e40d2c08a/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: deluan/navidrome
  # -- image tag
  tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [navidrome docs](https://www.navidrome.org/docs/usage/configuration-options/#environment-variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Log level. Useful for troubleshooting
  ND_LOGLEVEL: info
  # -- How long Navidrome will wait before closing web ui idle sessions
  ND_SESSIONTIMEOUT: 24h
  # -- Enables transcoding configuration in the UI
  ND_ENABLETRANSCODINGCONFIG: "true"
  # -- Folder where your music library is stored
  ND_MUSICFOLDER: /music
  # -- Enable extra endpoint with Prometheus metrics
  ND_PROMETHEUS_ENABLED: "false"
  # -- Enable sharing
  ND_ENABLESHARING: "false"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 4533
    monitor:
      # -- Enables or disables the serviceMonitor.
      enabled: false
      # -- Configures the endpoints for the serviceMonitor.
      # @default -- See values.yaml
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        location /metrics {
          deny all;
          return 403;
        }

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /data
  music:
    enabled: false
    mountPath: /music
