apiVersion: v2
name: remote-wake-sleep-on-lan
description: Web app to send Magic Packets to wake machines on your LAN
type: application
version: 0.1.5
appVersion: "latest"

home: https://github.com/djjudas21/charts/tree/main/charts/remote-wake-sleep-on-lan
keywords:
  - wakeonlan
  - wake
  - magicpacket
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
sources:
  - https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server
  - https://hub.docker.com/r/ex0nuss/remote-wake-sleep-on-lan-docker
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Fix array handling
