{{- if .Values.mariadbOperator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domainmod.fullname" . }}-mariadb-user
data:
  password: {{ .Values.mariadbOperator.auth.password | b64enc }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "domainmod.fullname" . }}
spec:
  mariaDbRef:
    name: {{ include "domainmod.fullname" . }}-mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.mariadbOperator.auth.username }}
spec:
  mariaDbRef:
    name: {{ include "domainmod.fullname" . }}-mariadb
  passwordSecretKeyRef:
    name: {{ include "domainmod.fullname" . }}-mariadb-user
    key: password
  maxUserConnections: 20
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ include "domainmod.fullname" . }}-{{ .Values.mariadbOperator.auth.username }}
spec:
  mariaDbRef:
    name: {{ include "domainmod.fullname" . }}-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: {{ include "domainmod.fullname" . }}
  table: "*"
  username: {{ .Values.mariadbOperator.auth.username }}
  grantOption: false
  host: "%"
{{- end }}